HW3 is completed
negen/otus_golang_hw pull request #6
Opened 2020-09-30 14:42 UTC by negen

## Домашнее задание №3 «Частотный анализ»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-09-30 16:42 UTC, kulti requested changes
Хорошее решение. Классно, что попробовали сделать вариант со звездочкой — в нем есть маленькая ошибочка в regClear.

Предлагаю поправить ошибку и замечания по чистоте кода.

2020-09-30 16:42 UTC, kulti commented on hw03_frequency_analysis/top.go
> +	result := make([]string, 0, 10)
Переменные лучше создавать максимально близко к месту использования. Там больше контекста для корректной инициализации. Так же при раннем выходе из метода, не будут создаваться лишние переменные.

2020-09-30 16:42 UTC, kulti commented on hw03_frequency_analysis/top.go
> +	sort.Sort(sort.Reverse(list))
Можно просто поменять порядок сортировки. Т.е. написать в Less: `return p[i].Value > p[j].Value`.

В итоге, можно будет не реализовывать свой тип, а использовать `sort.Slice`.

2020-09-30 16:42 UTC, kulti commented on hw03_frequency_analysis/top.go
> +			break
Можно сделать симпатичнее и очевиднее, если определить количество слов перед циклом. Тогда и result будет строго на нужное число элементов.

2020-09-30 16:42 UTC, kulti commented on hw03_frequency_analysis/top.go
> +	Value int
Count будет понятнее Value, т.к. Value абстрактное понятие.

2020-09-30 16:42 UTC, kulti commented on hw03_frequency_analysis/top.go
> +		regClear := regexp.MustCompile("[^a-zа-я0-9]+")
Эта регулярка зачем-то компилируется на каждой итерации цикла.

Так же она не учитывает слова с дефисами.

2020-09-30 16:42 UTC, kulti commented on hw03_frequency_analysis/top.go
> +	wordList := reg.Split(input, -1)
Эта регулярка не учитывает случай нескольких пробелов подряд. regClear потом подчистит, но зачем, если можно сразу чистый wordList сделать.

Еще можно `strings.Fields` использовать. Думаю, он эффективнее и понятнее будет.

2020-09-30 19:58 UTC, negen commented
@kulti 
замечания подправил, можно проверять

2020-10-01 08:18 UTC, kulti approved these changes
Теперь выгляди отлично. Основная задача решена хорошо. ДЗ принято - 10/10.

В задании со звездочкой еще можно поразбираться с нюансами (наличие лишних и отсутствие нужных пробелов вокруг знаков препинания, например). Предлагаю двигаться дальше, т.к. основная задача ДЗ "разобраться со слайсами и массивами" выполнена.

2020-10-01 08:22 UTC, merged